#!/bin/bash
#
#SBATCH --job-name=test
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=1
#SBATCH --time=2:00:00
#SBATCH --mem=50GB

module purge

singularity exec --nv \
            --overlay ~/conda_envs/pth1.10-cuda102-25GB-500K.sqf:ro \
            /scratch/work/public/singularity/cuda11.0-cudnn8-devel-ubuntu18.04.sif \
            bash -c "source /ext3/env.sh; export PYTHONPATH=../dataProviders:$PYTHONPATH; python test.py --folder_names $1 --x_forward 0 --n_forward 5 " $1
