#!/bin/bash
#
#SBATCH --job-name=sPhysNet
#SBATCH --nodes=1
#SBATCH --gres=gpu:rtx8000:1
#SBATCH --cpus-per-task=1
#SBATCH --time=24:00:00
#SBATCH --mem=14GB

module purge

singularity exec --nv \
            --overlay ~/conda_envs/pth1.10-cuda102-25GB-500K.sqf:ro \
            /scratch/work/public/singularity/cuda11.0-cudnn8-devel-ubuntu18.04.sif \
            bash -c "source /ext3/env.sh; export PYTHONPATH=../dataProviders:$PYTHONPATH; python train.py --config_name $1 " $1
